language: ruby
sudo: required
cache:
  bundler: true
rvm:
  - 2.3.1
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec
