# config/app.yml for rails-settings-cached
defaults: &defaults
  top_audio_quantity: 10
  price: 200000
  admin_per_page: 20

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
